GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzEzMDE1MTN9.F51DiZBsTzNYuRwn-cnf0moWu9LWx9J_8uk4tjYQXgA
Content-Type: application/json

###

GET http://localhost:3000/products/4

###

POST http://localhost:3000/products
content-type: application/json


{
"name": "Hanky the Christmas Poo",
"price": 300,
"integer": "",
"description": "the smelliest happiest live poo in December"
}

### 

PATCH http://localhost:3000/products/2
content-type: application/json


{
"name": "Banana",
"price": 3,
"description": "A yellow, elongated fruit. its best when no longer green"
}


###


DELETE http://localhost:3000/suppliers/7


###


# Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

  {
    "name": "Alice",
    "email": "Alice@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }


###

# Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "Alice@gmail.com",
    "password": "password"
  }

###


POST http://localhost:3000/products


  {
    "name": "Alice",
    "width": 640,
    "height": 480
  }
