@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE3MTk2MTZ9.7JwXEIyOFOmg7qi6cdn01R1AOuRL3lXB9KiX6L88xYo

### INDEX PRODUCTS

GET http://localhost:3000/products

### SHOW PRODUCTS
GET http://localhost:3000/products/2

### UPDATE PRODUCTS
PATCH http://localhost:3000/products/2
content-type: application/json
{
"name": "",
"price": ,
"description": "",
"supplier_id": 

}

### DELETE 
DELETE http://localhost:3000/suppliers/7


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

  {
    "name": "Alice",
    "email": "Alice@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "Nuke@gmail.com",
    "password": "password"
  }
### CREATE ORDERS
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  
  "product_id": 2,
  "quantity": 1
  
}
### SHOW ORDERS
GET http://localhost:3000/orders/10
Authorization: Bearer {{jwt}}
Content-Type: application/json

### INDEX ORDERS 
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Carted Products Create pass null in order_id

POST http://localhost:3000/carted_products
Content-Type: application/json

{
  "user_id": ,
  "product_id": ,
  "order_id": ,
  "quantity": ,
  "status": "carted"
}


