@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE3MTg4NzR9.cSVO_n9htsV4yXRV4V8zyJ5fHRge3aWEYD1-_gIe4As
GET http://localhost:3000/products
Authorization: {{jwt}}
Content-Type: application/json

### SHOW
GET http://localhost:3000/products/4

### UPDATE
PATCH http://localhost:3000/products/2
content-type: application/json
{
"name": "",
"price": ,
"description": "",
"supplier_id": 

}

### DELETE
DELETE http://localhost:3000/suppliers/7


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

  {
    "name": "Alice",
    "email": "Alice@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "Nuke@gmail.com",
    "password": "password"
  }
### CREATE
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 1
  
}
### SHOW
GET http://localhost:3000/orders/1
Authorization: {{jwt}}
Content-Type: application/json

### INDEX
GET http://localhost:3000/orders
Authorization: {{jwt}}
Content-Type: application/json





